# Generated by Django 3.1.2 on 2020-10-13 01:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import event.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=149, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=event.models.init)),
                ('end_date', models.DateField(default=event.models.end)),
                ('banner_1', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('use_banner_1', models.BooleanField(default=False)),
                ('banner_2', models.FileField(blank=True, null=True, upload_to='banners/')),
                ('use_banner_2', models.BooleanField(default=False)),
                ('link_1', models.URLField(blank=True, default='', null=True)),
                ('link_1_text', models.CharField(blank=True, max_length=300, null=True)),
                ('use_link_1', models.BooleanField(default=False)),
                ('link_2', models.URLField(blank=True, default='', null=True)),
                ('link_2_text', models.CharField(blank=True, max_length=300, null=True)),
                ('use_link_2', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.country')),
            ],
        ),
    ]
