# Generated by Django 3.1.2 on 2020-10-13 02:01

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_1',
            field=models.FileField(blank=True, default='banners/default.jpeg', null=True, upload_to='banners/'),
        ),
    ]
